<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2ba20531-da2b-4ccd-b9f3-5197c960a14d</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>
</Project>
